# Generated by Django 3.2 on 2021-09-27 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_dimension', models.CharField(max_length=255)),
                ('date_creation_dimension', models.DateField(auto_now_add=True)),
                ('archive_dimension', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_division', models.CharField(max_length=25)),
                ('date_de_creation_division', models.DateField(auto_now_add=True)),
                ('archive_division', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_observation', models.CharField(max_length=255)),
                ('date_creation_observation', models.DateField(auto_now_add=True)),
                ('archive_observation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tombe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastre_tombe', models.IntegerField()),
                ('emplacement_tombe', models.CharField(max_length=255)),
                ('nom_defunt_tombe', models.CharField(max_length=255)),
                ('naissance_defunt_tombe', models.DateField()),
                ('deces_defunt_tombe', models.DateField()),
                ('age_defunt_tombe', models.IntegerField()),
                ('dimension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cimetieres.dimension')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cimetieres.division')),
                ('observation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cimetieres.observation')),
            ],
        ),
    ]
