# Generated by Django 3.2 on 2021-09-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cimetieres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tombe',
            name='archive_tombe',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tombe',
            name='date_enregistrement',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='archive_dimension',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='nom_dimension',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='archive_division',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='date_de_creation_division',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='nom_division',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='archive_observation',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='date_creation_observation',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='nom_observation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tombe',
            name='age_defunt_tombe',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tombe',
            name='cadastre_tombe',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tombe',
            name='deces_defunt_tombe',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tombe',
            name='emplacement_tombe',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tombe',
            name='naissance_defunt_tombe',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tombe',
            name='nom_defunt_tombe',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
