# Generated by Django 3.2 on 2021-10-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cimetieres', '0002_alter_tombe_age_defunt_tombe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tombe',
            name='deces_defunt_tombe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
