# Generated by Django 3.2 on 2021-10-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cimetieres', '0006_alter_tombe_age_defunt_tombe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tombe',
            name='age_defunt_tombe',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tombe',
            name='division',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tombe',
            name='emplacement_tombe',
            field=models.CharField(blank=True, max_length=251, null=True),
        ),
        migrations.AlterField(
            model_name='tombe',
            name='naissance_defunt_tombe',
            field=models.CharField(blank=True, default=None, max_length=253, null=True),
        ),
        migrations.AlterField(
            model_name='tombe',
            name='nom_defunt_tombe',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='tombe',
            name='observation',
            field=models.CharField(blank=True, max_length=249, null=True),
        ),
    ]
