# Generated by Django 3.2 on 2021-10-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cimetieres', '0007_auto_20211018_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tombe',
            name='nom_defunt_tombe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
