# Generated by Django 3.2 on 2021-10-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cimetieres', '0009_alter_tombe_cadastre_tombe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tombe',
            name='cadastre_tombe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
